version: '3.8'

services:
  taxi-fare-prediction:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taxi-fare-prediction
    ports:
      - "8000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    volumes:
      - ./data:/app/data
      - ./templates:/app/templates
      - ./static:/app/static
    restart: unless-stopped